version: "3"

networks:
  mess-ppa:

services:
  server:
    image: node:16-alpine
    container_name: server-mess-ppa
    restart: on-failure
    volumes:
      - ./app/server:/var/www/html/server
    working_dir: /var/www/html/server
    depends_on:
      - adminer
      - mariadb
      - client
    ports:
      - 1001:1001
    command:
      ["sh", "-c", "npm run dev"]
    networks:
      - mess-ppa

  client:
    image: node:16-alpine
    container_name: client-mess-ppa
    restart: on-failure
    volumes:
      - ./app/client:/var/www/html/client
    working_dir: /var/www/html/client
    ports:
      - 1010:5173
    command:
      ["sh", "-c", "npm run dev"]
    networks:
      - mess-ppa

  npm-server:
    image: node:16-alpine
    container_name: npm-mess-ppa
    volumes:
      - ./app/server:/var/www/html/server
    working_dir: /var/www/html/server
    networks:
      - mess-ppa

  npm-client:
    image: node:16-alpine
    container_name: npm-mess-ppa
    volumes:
      - ./app/client:/var/www/html/client
    working_dir: /var/www/html/client
    networks:
      - mess-ppa

  mariadb:
    image: mariadb:10.6.4
    container_name: mariadb-mess-ppa
    tty: true
    restart: on-failure
    ports:
      - 1002:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MARIADB_DATABASE: mess-ppa
      MARIADB_USER: root
      MARIADB_PASSWORD: buyung
      MARIADB_ROOT_PASSWORD: buyung
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    networks:
      - mess-ppa

  adminer:
    build:
      context: .
      dockerfile: adminer.dockerfile
    container_name: adminer-mess-ppa
    restart: on-failure
    ports:
      - 1003:8080
    networks:
      - mess-ppa
